legal:
  rate_cap_per_hour: 450         # USD
  flag_keywords: ["rush", "emergency", "expedite"]
  duplicate_window_days: 90
hr:
  max_daily_hours: 12
  weekend_overtime_requires_approval: true
transport:
  accessorial_caps:
    detention: 150
    lumper: 100
    liftgate: 120
  fuel_surcharge_pct_max: 0.35
accounting:
  duplicate_invoice_amount_tolerance: 1.00   # USD
