version: 1
domains:
  legal:
    rate_caps_per_role:
      Partner: 450
      Associate: 300
      Paralegal: 150
    duplicate_tolerance: 1.00   # amount $ tolerance
    narrative_keywords: ["rush","expedite","emergency","admin","internal"]
  hr:
    max_daily_hours: 8.0
    weekend_requires_approval: true
  transport:
    accessorial_caps:
      detention: 150
      lumper: 120
      liftgate: 90
    max_fuel_surcharge_percent: 28
  accounting:
    duplicate_amount_tolerance: 1.00
