name: Operion CI (Windows)
on:
  push: { branches: ["**"] }
  pull_request: { branches: ["main"] }
jobs:
  console-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Prepare
        run: |
          cd console
          if [ -f package.json ]; then
            npm i || true
            npx vite build || true
          else
            echo 'no console directory yet'
          fi  ci:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PowerShell
        uses: PowerShell/PowerShell@v1
        with: { pwsh-version: "7.4.x" }
      - name: Lint
        shell: pwsh
        run: |
          Set-Location $env:GITHUB_WORKSPACE
          pwsh -File ops/lint.ps1
      - name: Self-test
        shell: pwsh
        run: |
          Set-Location $env:GITHUB_WORKSPACE
          pwsh -File ops/self_test.ps1 -CI
      - name: Snapshot
        shell: pwsh
        run: |
          Set-Location $env:GITHUB_WORKSPACE
          pwsh -File ops/snapshot.ps1
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: operion-logs
          path: |
            _logs\parity_*.log
            _logs\lint_*.txt
            _logs\snapshot_*.txt
          if-no-files-found: ignore

